[2022-08-02 10:36:53,457] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Demo.records_saving manual__2022-08-02T10:36:37.553293+00:00 [queued]>
[2022-08-02 10:36:53,468] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Demo.records_saving manual__2022-08-02T10:36:37.553293+00:00 [queued]>
[2022-08-02 10:36:53,469] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-02 10:36:53,469] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-02 10:36:53,470] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-02 10:36:53,488] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): records_saving> on 2022-08-02 10:36:37.553293+00:00
[2022-08-02 10:36:53,493] {standard_task_runner.py:52} INFO - Started process 5695 to run task
[2022-08-02 10:36:53,497] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Demo', 'records_saving', 'manual__2022-08-02T10:36:37.553293+00:00', '--job-id', '255', '--raw', '--subdir', 'DAGS_FOLDER/demo.py', '--cfg-path', '/tmp/tmpxywjk3o2', '--error-file', '/tmp/tmpwdupi4jt']
[2022-08-02 10:36:53,497] {standard_task_runner.py:80} INFO - Job 255: Subtask records_saving
[2022-08-02 10:36:53,567] {task_command.py:371} INFO - Running <TaskInstance: Demo.records_saving manual__2022-08-02T10:36:37.553293+00:00 [running]> on host 31353b71d6cb
[2022-08-02 10:36:53,649] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Demo
AIRFLOW_CTX_TASK_ID=records_saving
AIRFLOW_CTX_EXECUTION_DATE=2022-08-02T10:36:37.553293+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-02T10:36:37.553293+00:00
[2022-08-02 10:36:53,660] {base.py:68} INFO - Using connection ID 'postgres_demo' for task execution.
[2022-08-02 10:36:53,664] {dbapi.py:231} INFO - Running statement: CREATE TABLE IF NOT EXISTS public."Files"
                            (
                                id integer NOT NULL,
                                name varchar(80),
                                size bigint,
                                CONSTRAINT "Files_pkey" PRIMARY KEY (id)
                            ), parameters: None
[2022-08-02 10:36:53,682] {base.py:68} INFO - Using connection ID 'postgres_demo' for task execution.
[2022-08-02 10:36:53,685] {dbapi.py:231} INFO - Running statement: INSERT INTO public."Files"(
                                id, size)
                                VALUES (0,100);, parameters: None
[2022-08-02 10:36:53,687] {dbapi.py:239} INFO - Rows affected: 1
[2022-08-02 10:36:53,698] {base.py:68} INFO - Using connection ID 'postgres_demo' for task execution.
[2022-08-02 10:36:53,701] {dbapi.py:231} INFO - Running statement: INSERT INTO public."Files"(
                                id, size)
                                VALUES (1,101);, parameters: None
[2022-08-02 10:36:53,702] {dbapi.py:239} INFO - Rows affected: 1
[2022-08-02 10:36:53,705] {python.py:173} INFO - Done. Returned value was: None
[2022-08-02 10:36:53,719] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=Demo, task_id=records_saving, execution_date=20220802T103637, start_date=20220802T103653, end_date=20220802T103653
[2022-08-02 10:36:53,749] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-02 10:36:53,793] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
