[2022-08-01 11:05:57,649] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Demo.container_creation manual__2022-08-01T11:05:55.142351+00:00 [queued]>
[2022-08-01 11:05:57,669] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Demo.container_creation manual__2022-08-01T11:05:55.142351+00:00 [queued]>
[2022-08-01 11:05:57,670] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-01 11:05:57,670] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-01 11:05:57,672] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-01 11:05:57,701] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): container_creation> on 2022-08-01 11:05:55.142351+00:00
[2022-08-01 11:05:57,708] {standard_task_runner.py:52} INFO - Started process 2343 to run task
[2022-08-01 11:05:57,713] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Demo', 'container_creation', 'manual__2022-08-01T11:05:55.142351+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/demo.py', '--cfg-path', '/tmp/tmptrvsmrqk', '--error-file', '/tmp/tmp6uv6884q']
[2022-08-01 11:05:57,715] {standard_task_runner.py:80} INFO - Job 69: Subtask container_creation
[2022-08-01 11:05:57,870] {task_command.py:371} INFO - Running <TaskInstance: Demo.container_creation manual__2022-08-01T11:05:55.142351+00:00 [running]> on host 31353b71d6cb
[2022-08-01 11:05:58,114] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Demo
AIRFLOW_CTX_TASK_ID=container_creation
AIRFLOW_CTX_EXECUTION_DATE=2022-08-01T11:05:55.142351+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-01T11:05:55.142351+00:00
[2022-08-01 11:05:58,117] {confidential_client_secret_sample.py:53} INFO - No suitable token exists in cache. Let's get a new one from AAD.
[2022-08-01 11:05:58,396] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/demo.py", line 12, in create_container
    waves_dict_ids,transcriptions_dict_ids=API_Call_Result(result)
  File "/opt/airflow/dags/external_files/confidential_client_secret_sample.py", line 57, in API_Call_Result
    waves_dict_ids=get_files_ids("endpoint_waves")
  File "/opt/airflow/dags/external_files/confidential_client_secret_sample.py", line 12, in get_files_ids
    headers={'Authorization': 'Bearer ' + result['access_token']}, ).json()
TypeError: 'NoneType' object is not subscriptable
[2022-08-01 11:05:58,424] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=Demo, task_id=container_creation, execution_date=20220801T110555, start_date=20220801T110557, end_date=20220801T110558
[2022-08-01 11:05:58,451] {standard_task_runner.py:97} ERROR - Failed to execute job 69 for task container_creation ('NoneType' object is not subscriptable; 2343)
[2022-08-01 11:05:58,487] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-01 11:05:58,628] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
