[2022-08-02 10:27:44,074] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Demo.records_saving manual__2022-08-02T10:27:28.152315+00:00 [queued]>
[2022-08-02 10:27:44,087] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Demo.records_saving manual__2022-08-02T10:27:28.152315+00:00 [queued]>
[2022-08-02 10:27:44,088] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-02 10:27:44,088] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-02 10:27:44,090] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-02 10:27:44,109] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): records_saving> on 2022-08-02 10:27:28.152315+00:00
[2022-08-02 10:27:44,114] {standard_task_runner.py:52} INFO - Started process 5238 to run task
[2022-08-02 10:27:44,118] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Demo', 'records_saving', 'manual__2022-08-02T10:27:28.152315+00:00', '--job-id', '239', '--raw', '--subdir', 'DAGS_FOLDER/demo.py', '--cfg-path', '/tmp/tmpzdhajz4x', '--error-file', '/tmp/tmp4b80nd1q']
[2022-08-02 10:27:44,119] {standard_task_runner.py:80} INFO - Job 239: Subtask records_saving
[2022-08-02 10:27:44,197] {task_command.py:371} INFO - Running <TaskInstance: Demo.records_saving manual__2022-08-02T10:27:28.152315+00:00 [running]> on host 31353b71d6cb
[2022-08-02 10:27:44,280] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Demo
AIRFLOW_CTX_TASK_ID=records_saving
AIRFLOW_CTX_EXECUTION_DATE=2022-08-02T10:27:28.152315+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-02T10:27:28.152315+00:00
[2022-08-02 10:27:44,290] {base.py:68} INFO - Using connection ID 'postgres_demo' for task execution.
[2022-08-02 10:27:44,294] {dbapi.py:231} INFO - Running statement: CREATE TABLE IF NOT EXISTS public."Files"
                            (
                                id integer NOT NULL,
                                name character(80)[] NOT NULL,
                                size bigint,
                                CONSTRAINT "Files_pkey" PRIMARY KEY (id)
                            ), parameters: None
[2022-08-02 10:27:44,302] {base.py:68} INFO - Using connection ID 'postgres_demo' for task execution.
[2022-08-02 10:27:44,305] {dbapi.py:231} INFO - Running statement: INSERT INTO public."Files"(
                                id, name, size)
                                VALUES (0,10,100);, parameters: None
[2022-08-02 10:27:44,307] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/demo.py", line 64, in save_records
    postgres_hook.run(sql)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 211, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 235, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.DatatypeMismatch: column "name" is of type character[] but expression is of type integer
LINE 3:                                 VALUES (0,10,100);
                                                  ^
HINT:  You will need to rewrite or cast the expression.

[2022-08-02 10:27:44,319] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=Demo, task_id=records_saving, execution_date=20220802T102728, start_date=20220802T102744, end_date=20220802T102744
[2022-08-02 10:27:44,335] {standard_task_runner.py:97} ERROR - Failed to execute job 239 for task records_saving (column "name" is of type character[] but expression is of type integer
LINE 3:                                 VALUES (0,10,100);
                                                  ^
HINT:  You will need to rewrite or cast the expression.
; 5238)
[2022-08-02 10:27:44,370] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-02 10:27:44,421] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
