[2022-08-02 10:47:03,937] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Demo.records_saving manual__2022-08-02T10:46:48.583417+00:00 [queued]>
[2022-08-02 10:47:03,949] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Demo.records_saving manual__2022-08-02T10:46:48.583417+00:00 [queued]>
[2022-08-02 10:47:03,949] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-02 10:47:03,950] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-02 10:47:03,951] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-02 10:47:03,972] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): records_saving> on 2022-08-02 10:46:48.583417+00:00
[2022-08-02 10:47:03,978] {standard_task_runner.py:52} INFO - Started process 6201 to run task
[2022-08-02 10:47:03,982] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Demo', 'records_saving', 'manual__2022-08-02T10:46:48.583417+00:00', '--job-id', '272', '--raw', '--subdir', 'DAGS_FOLDER/demo.py', '--cfg-path', '/tmp/tmp047_jhq8', '--error-file', '/tmp/tmpp3ul7_z4']
[2022-08-02 10:47:03,983] {standard_task_runner.py:80} INFO - Job 272: Subtask records_saving
[2022-08-02 10:47:04,060] {task_command.py:371} INFO - Running <TaskInstance: Demo.records_saving manual__2022-08-02T10:46:48.583417+00:00 [running]> on host 31353b71d6cb
[2022-08-02 10:47:04,145] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Demo
AIRFLOW_CTX_TASK_ID=records_saving
AIRFLOW_CTX_EXECUTION_DATE=2022-08-02T10:46:48.583417+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-02T10:46:48.583417+00:00
[2022-08-02 10:47:04,157] {base.py:68} INFO - Using connection ID 'postgres_demo' for task execution.
[2022-08-02 10:47:04,161] {dbapi.py:231} INFO - Running statement: CREATE TABLE IF NOT EXISTS public."Files"
                            (
                                id integer NOT NULL,
                                name varchar(50) NOT NULL,
                                size bigint,
                                CONSTRAINT "Files_pkey" PRIMARY KEY (id)
                            ), parameters: None
[2022-08-02 10:47:04,181] {base.py:68} INFO - Using connection ID 'postgres_demo' for task execution.
[2022-08-02 10:47:04,184] {dbapi.py:231} INFO - Running statement: INSERT INTO public."Files"(
                                id,name,size)
                                VALUES(0,'houssem',100);, parameters: None
[2022-08-02 10:47:04,186] {dbapi.py:239} INFO - Rows affected: 1
[2022-08-02 10:47:04,196] {base.py:68} INFO - Using connection ID 'postgres_demo' for task execution.
[2022-08-02 10:47:04,200] {dbapi.py:231} INFO - Running statement: INSERT INTO public."Files"(
                                id,name,size)
                                VALUES(1,'houssem',101);, parameters: None
[2022-08-02 10:47:04,201] {dbapi.py:239} INFO - Rows affected: 1
[2022-08-02 10:47:04,205] {python.py:173} INFO - Done. Returned value was: None
[2022-08-02 10:47:04,221] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=Demo, task_id=records_saving, execution_date=20220802T104648, start_date=20220802T104703, end_date=20220802T104704
[2022-08-02 10:47:04,275] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-02 10:47:04,328] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
