[2022-07-12 23:48:14,773] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Demo.demo manual__2022-07-12T23:48:08.705979+00:00 [queued]>
[2022-07-12 23:48:14,825] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Demo.demo manual__2022-07-12T23:48:08.705979+00:00 [queued]>
[2022-07-12 23:48:14,827] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-12 23:48:14,828] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-12 23:48:14,829] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-12 23:48:15,561] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): demo> on 2022-07-12 23:48:08.705979+00:00
[2022-07-12 23:48:15,569] {standard_task_runner.py:52} INFO - Started process 1681 to run task
[2022-07-12 23:48:15,580] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Demo', 'demo', 'manual__2022-07-12T23:48:08.705979+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/demo.py', '--cfg-path', '/tmp/tmp3wkjb2c6', '--error-file', '/tmp/tmp1uwfnrbq']
[2022-07-12 23:48:15,581] {standard_task_runner.py:80} INFO - Job 16: Subtask demo
[2022-07-12 23:48:16,107] {task_command.py:370} INFO - Running <TaskInstance: Demo.demo manual__2022-07-12T23:48:08.705979+00:00 [running]> on host 939e047cba2c
[2022-07-12 23:48:17,266] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Demo
AIRFLOW_CTX_TASK_ID=demo
AIRFLOW_CTX_EXECUTION_DATE=2022-07-12T23:48:08.705979+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-12T23:48:08.705979+00:00
[2022-07-12 23:48:17,353] {base.py:68} INFO - Using connection ID 'demo' for task execution.
[2022-07-12 23:48:17,388] {logging_mixin.py:115} INFO - <***.providers.microsoft.azure.hooks.wasb.WasbHook object at 0x7f9564a651d0>
[2022-07-12 23:48:17,401] {logging_mixin.py:115} INFO - connection made successfully
[2022-07-12 23:48:17,497] {_universal.py:476} INFO - Request URL: 'http://127.0.0.1:10000/devstoreaccount1/demo?restype=REDACTED&comp=REDACTED&delimiter=REDACTED'
Request method: 'GET'
Request headers:
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.8.1 Python/3.7.13 (Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-debian-11.3)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '1a3d0c46-023d-11ed-a5df-0242ac120004'
    'Authorization': 'REDACTED'
No body was attached to the request
[2022-07-12 23:48:37,189] {_universal.py:476} INFO - Request URL: 'http://127.0.0.1:10000/devstoreaccount1/demo?restype=REDACTED&comp=REDACTED&delimiter=REDACTED'
Request method: 'GET'
Request headers:
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.8.1 Python/3.7.13 (Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-debian-11.3)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '25fbebce-023d-11ed-a5df-0242ac120004'
    'Authorization': 'REDACTED'
No body was attached to the request
[2022-07-12 23:49:00,403] {_universal.py:476} INFO - Request URL: 'http://127.0.0.1:10000/devstoreaccount1/demo?restype=REDACTED&comp=REDACTED&delimiter=REDACTED'
Request method: 'GET'
Request headers:
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.8.1 Python/3.7.13 (Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-debian-11.3)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '33d22e16-023d-11ed-a5df-0242ac120004'
    'Authorization': 'REDACTED'
No body was attached to the request
[2022-07-12 23:49:39,747] {_universal.py:476} INFO - Request URL: 'http://127.0.0.1:10000/devstoreaccount1/demo?restype=REDACTED&comp=REDACTED&delimiter=REDACTED'
Request method: 'GET'
Request headers:
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.8.1 Python/3.7.13 (Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-debian-11.3)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '4b4592cc-023d-11ed-a5df-0242ac120004'
    'Authorization': 'REDACTED'
No body was attached to the request
[2022-07-12 23:49:39,756] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/demo.py", line 11, in demo
    x=test.get_blobs_list(container_name="demo")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 231, in get_blobs_list
    for blob in blobs:
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/core/paging.py", line 129, in __next__
    return next(self._page_iterator)
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/core/paging.py", line 76, in __next__
    self._response = self._get_next(self.continuation_token)
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/storage/blob/_list_blobs_helper.py", line 77, in _get_next_cb
    use_location=self.location_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/storage/blob/_generated/operations/_container_operations.py", line 1572, in list_blob_hierarchy_segment
    pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 211, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 2 more times]
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/core/pipeline/policies/_redirect.py", line 158, in send
    response = self.next.send(request)
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/storage/blob/_shared/policies.py", line 515, in send
    raise err
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/storage/blob/_shared/policies.py", line 489, in send
    response = self.next.send(request)
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 1 more time]
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/storage/blob/_shared/policies.py", line 290, in send
    response = self.next.send(request)
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 103, in send
    self._sender.send(request.http_request, **request.context.options),
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/storage/blob/_shared/base_client.py", line 333, in send
    return self._transport.send(request, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/core/pipeline/transport/_requests_basic.py", line 361, in send
    raise error
azure.core.exceptions.ServiceRequestError: <urllib3.connection.HTTPConnection object at 0x7f95649cfd10>: Failed to establish a new connection: [Errno 111] Connection refused
[2022-07-12 23:49:39,804] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Demo, task_id=demo, execution_date=20220712T234808, start_date=20220712T234814, end_date=20220712T234939
[2022-07-12 23:49:44,778] {standard_task_runner.py:97} ERROR - Failed to execute job 16 for task demo (<urllib3.connection.HTTPConnection object at 0x7f95649cfd10>: Failed to establish a new connection: [Errno 111] Connection refused; 1681)
[2022-07-12 23:49:44,820] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-12 23:49:45,207] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
