[2022-08-02 10:20:47,878] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Demo.records_saving manual__2022-08-02T10:20:31.126961+00:00 [queued]>
[2022-08-02 10:20:47,889] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Demo.records_saving manual__2022-08-02T10:20:31.126961+00:00 [queued]>
[2022-08-02 10:20:47,890] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-02 10:20:47,890] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-02 10:20:47,891] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-02 10:20:47,911] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): records_saving> on 2022-08-02 10:20:31.126961+00:00
[2022-08-02 10:20:47,916] {standard_task_runner.py:52} INFO - Started process 4899 to run task
[2022-08-02 10:20:47,919] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Demo', 'records_saving', 'manual__2022-08-02T10:20:31.126961+00:00', '--job-id', '227', '--raw', '--subdir', 'DAGS_FOLDER/demo.py', '--cfg-path', '/tmp/tmpksjn8c0s', '--error-file', '/tmp/tmpe1mw600b']
[2022-08-02 10:20:47,920] {standard_task_runner.py:80} INFO - Job 227: Subtask records_saving
[2022-08-02 10:20:47,996] {task_command.py:371} INFO - Running <TaskInstance: Demo.records_saving manual__2022-08-02T10:20:31.126961+00:00 [running]> on host 31353b71d6cb
[2022-08-02 10:20:48,081] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Demo
AIRFLOW_CTX_TASK_ID=records_saving
AIRFLOW_CTX_EXECUTION_DATE=2022-08-02T10:20:31.126961+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-02T10:20:31.126961+00:00
[2022-08-02 10:20:48,092] {base.py:68} INFO - Using connection ID 'postgres_demo' for task execution.
[2022-08-02 10:20:48,096] {dbapi.py:231} INFO - Running statement: CREATE TABLE IF NOT EXISTS public."Files"
                            (
                                id integer NOT NULL,
                                name character(80)[] COLLATE pg_catalog."default" NOT NULL,
                                size bigint,
                                CONSTRAINT "Files_pkey" PRIMARY KEY (id)
                            ), parameters: None
[2022-08-02 10:20:48,103] {base.py:68} INFO - Using connection ID 'postgres_demo' for task execution.
[2022-08-02 10:20:48,107] {dbapi.py:231} INFO - Running statement: INSERT INTO public."Files"(
                                id, name, size)
                                VALUES (0,houssem,100);, parameters: None
[2022-08-02 10:20:48,108] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/demo.py", line 64, in save_records
    postgres_hook.run(sql)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 211, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 235, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "houssem" does not exist
LINE 3:                                 VALUES (0,houssem,100);
                                                  ^

[2022-08-02 10:20:48,122] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=Demo, task_id=records_saving, execution_date=20220802T102031, start_date=20220802T102047, end_date=20220802T102048
[2022-08-02 10:20:48,137] {standard_task_runner.py:97} ERROR - Failed to execute job 227 for task records_saving (column "houssem" does not exist
LINE 3:                                 VALUES (0,houssem,100);
                                                  ^
; 4899)
[2022-08-02 10:20:48,172] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-02 10:20:48,229] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
