[2022-07-28 11:50:46,825] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Demo.container_creation manual__2022-07-28T11:50:45.460736+00:00 [queued]>
[2022-07-28 11:50:46,835] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Demo.container_creation manual__2022-07-28T11:50:45.460736+00:00 [queued]>
[2022-07-28 11:50:46,835] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-28 11:50:46,836] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-07-28 11:50:46,836] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-28 11:50:46,851] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): container_creation> on 2022-07-28 11:50:45.460736+00:00
[2022-07-28 11:50:46,856] {standard_task_runner.py:52} INFO - Started process 521 to run task
[2022-07-28 11:50:46,860] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Demo', 'container_creation', 'manual__2022-07-28T11:50:45.460736+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/demo.py', '--cfg-path', '/tmp/tmp998jirxs', '--error-file', '/tmp/tmp0uyipgly']
[2022-07-28 11:50:46,861] {standard_task_runner.py:80} INFO - Job 8: Subtask container_creation
[2022-07-28 11:50:46,929] {task_command.py:371} INFO - Running <TaskInstance: Demo.container_creation manual__2022-07-28T11:50:45.460736+00:00 [running]> on host 949e67af4713
[2022-07-28 11:50:47,008] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Demo
AIRFLOW_CTX_TASK_ID=container_creation
AIRFLOW_CTX_EXECUTION_DATE=2022-07-28T11:50:45.460736+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-28T11:50:45.460736+00:00
[2022-07-28 11:50:47,018] {base.py:68} INFO - Using connection ID 'azure_demo' for task execution.
[2022-07-28 11:50:47,020] {logging_mixin.py:115} INFO - <***.providers.microsoft.azure.hooks.wasb.WasbHook object at 0x7f7d9bb8ef90>
[2022-07-28 11:50:47,021] {logging_mixin.py:115} INFO - connection made successfully
[2022-07-28 11:50:47,024] {_universal.py:476} INFO - Request URL: 'http://azurite/devstoreaccount1/demo?restype=REDACTED'
Request method: 'PUT'
Request headers:
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.8.1 Python/3.7.13 (Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-debian-11.4)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '84c642aa-0e6b-11ed-bf2c-0242ac120006'
    'Authorization': 'REDACTED'
No body was attached to the request
[2022-07-28 11:51:06,674] {_universal.py:476} INFO - Request URL: 'http://azurite/devstoreaccount1/demo?restype=REDACTED'
Request method: 'PUT'
Request headers:
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.8.1 Python/3.7.13 (Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-debian-11.4)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '907cd064-0e6b-11ed-bf2c-0242ac120006'
    'Authorization': 'REDACTED'
No body was attached to the request
[2022-07-28 11:51:32,565] {_universal.py:476} INFO - Request URL: 'http://azurite/devstoreaccount1/demo?restype=REDACTED'
Request method: 'PUT'
Request headers:
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.8.1 Python/3.7.13 (Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-debian-11.4)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '9feb3374-0e6b-11ed-bf2c-0242ac120006'
    'Authorization': 'REDACTED'
No body was attached to the request
[2022-07-28 11:52:13,804] {_universal.py:476} INFO - Request URL: 'http://azurite/devstoreaccount1/demo?restype=REDACTED'
Request method: 'PUT'
Request headers:
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.8.1 Python/3.7.13 (Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-debian-11.4)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'b87ffd20-0e6b-11ed-bf2c-0242ac120006'
    'Authorization': 'REDACTED'
No body was attached to the request
[2022-07-28 11:52:13,807] {wasb.py:386} INFO - Error while attempting to create container 'demo': <urllib3.connection.HTTPConnection object at 0x7f7d9bafb810>: Failed to establish a new connection: [Errno 111] Connection refused
[2022-07-28 11:52:13,808] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/demo.py", line 14, in create_container
    test.create_container(container_name="demo")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 367, in create_container
    container_client.create_container()
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/storage/blob/_container_client.py", line 298, in create_container
    **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/storage/blob/_generated/operations/_container_operations.py", line 128, in create
    pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 211, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 2 more times]
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/core/pipeline/policies/_redirect.py", line 158, in send
    response = self.next.send(request)
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/storage/blob/_shared/policies.py", line 515, in send
    raise err
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/storage/blob/_shared/policies.py", line 489, in send
    response = self.next.send(request)
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 1 more time]
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/storage/blob/_shared/policies.py", line 290, in send
    response = self.next.send(request)
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 103, in send
    self._sender.send(request.http_request, **request.context.options),
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/storage/blob/_shared/base_client.py", line 333, in send
    return self._transport.send(request, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/core/pipeline/transport/_requests_basic.py", line 361, in send
    raise error
azure.core.exceptions.ServiceRequestError: <urllib3.connection.HTTPConnection object at 0x7f7d9bafb810>: Failed to establish a new connection: [Errno 111] Connection refused
[2022-07-28 11:52:13,825] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=Demo, task_id=container_creation, execution_date=20220728T115045, start_date=20220728T115046, end_date=20220728T115213
[2022-07-28 11:52:13,841] {standard_task_runner.py:97} ERROR - Failed to execute job 8 for task container_creation (<urllib3.connection.HTTPConnection object at 0x7f7d9bafb810>: Failed to establish a new connection: [Errno 111] Connection refused; 521)
[2022-07-28 11:52:13,873] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-28 11:52:13,917] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
