[2022-07-12 22:54:41,020] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Demo.demo manual__2022-07-12T22:54:34.815283+00:00 [queued]>
[2022-07-12 22:54:41,055] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Demo.demo manual__2022-07-12T22:54:34.815283+00:00 [queued]>
[2022-07-12 22:54:41,056] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-12 22:54:41,056] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-12 22:54:41,057] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-12 22:54:41,383] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): demo> on 2022-07-12 22:54:34.815283+00:00
[2022-07-12 22:54:41,392] {standard_task_runner.py:52} INFO - Started process 140 to run task
[2022-07-12 22:54:41,402] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Demo', 'demo', 'manual__2022-07-12T22:54:34.815283+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/demo.py', '--cfg-path', '/tmp/tmpgh1u1m1c', '--error-file', '/tmp/tmptjmt4m6v']
[2022-07-12 22:54:41,404] {standard_task_runner.py:80} INFO - Job 13: Subtask demo
[2022-07-12 22:54:41,792] {task_command.py:370} INFO - Running <TaskInstance: Demo.demo manual__2022-07-12T22:54:34.815283+00:00 [running]> on host 939e047cba2c
[2022-07-12 22:54:42,757] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Demo
AIRFLOW_CTX_TASK_ID=demo
AIRFLOW_CTX_EXECUTION_DATE=2022-07-12T22:54:34.815283+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-12T22:54:34.815283+00:00
[2022-07-12 22:54:42,806] {base.py:68} INFO - Using connection ID 'demo' for task execution.
[2022-07-12 22:54:42,819] {_universal.py:476} INFO - Request URL: 'http://127.0.0.1:10000/devstoreaccount1/demo/example_2.json'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.8.1 Python/3.7.13 (Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-debian-11.3)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '9e261064-0235-11ed-b44b-0242ac120004'
    'Authorization': 'REDACTED'
No body was attached to the request
[2022-07-12 22:55:01,441] {_universal.py:476} INFO - Request URL: 'http://127.0.0.1:10000/devstoreaccount1/demo/example_2.json'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.8.1 Python/3.7.13 (Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-debian-11.3)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'a93fd188-0235-11ed-b44b-0242ac120004'
    'Authorization': 'REDACTED'
No body was attached to the request
[2022-07-12 22:55:24,687] {_universal.py:476} INFO - Request URL: 'http://127.0.0.1:10000/devstoreaccount1/demo/example_2.json'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.8.1 Python/3.7.13 (Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-debian-11.3)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'b71ad802-0235-11ed-b44b-0242ac120004'
    'Authorization': 'REDACTED'
No body was attached to the request
[2022-07-12 22:56:07,593] {_universal.py:476} INFO - Request URL: 'http://127.0.0.1:10000/devstoreaccount1/demo/example_2.json'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.8.1 Python/3.7.13 (Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-debian-11.3)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'd0adc5ae-0235-11ed-b44b-0242ac120004'
    'Authorization': 'REDACTED'
No body was attached to the request
[2022-07-12 22:56:07,599] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/demo.py", line 9, in demo
    file=test.read_file(container_name="demo",blob_name="example_2.json")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 310, in read_file
    return self.download(container_name, blob_name, **kwargs).content_as_text()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 354, in download
    return blob_client.download_blob(offset=offset, length=length, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/core/tracing/decorator.py", line 73, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/storage/blob/_blob_client.py", line 828, in download_blob
    return StorageStreamDownloader(**options)
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/storage/blob/_download.py", line 349, in __init__
    self._response = self._initial_request()
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/storage/blob/_download.py", line 392, in _initial_request
    **self._request_options
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/storage/blob/_generated/operations/_blob_operations.py", line 179, in download
    pipeline_response = self._client._pipeline.run(request, stream=True, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 211, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 2 more times]
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/core/pipeline/policies/_redirect.py", line 158, in send
    response = self.next.send(request)
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/storage/blob/_shared/policies.py", line 515, in send
    raise err
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/storage/blob/_shared/policies.py", line 489, in send
    response = self.next.send(request)
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 1 more time]
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/storage/blob/_shared/policies.py", line 290, in send
    response = self.next.send(request)
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 103, in send
    self._sender.send(request.http_request, **request.context.options),
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/storage/blob/_shared/base_client.py", line 333, in send
    return self._transport.send(request, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/azure/core/pipeline/transport/_requests_basic.py", line 361, in send
    raise error
azure.core.exceptions.ServiceRequestError: <urllib3.connection.HTTPConnection object at 0x7f9564a53090>: Failed to establish a new connection: [Errno 111] Connection refused
[2022-07-12 22:56:07,826] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Demo, task_id=demo, execution_date=20220712T225434, start_date=20220712T225441, end_date=20220712T225607
[2022-07-12 22:56:08,189] {standard_task_runner.py:97} ERROR - Failed to execute job 13 for task demo (<urllib3.connection.HTTPConnection object at 0x7f9564a53090>: Failed to establish a new connection: [Errno 111] Connection refused; 140)
[2022-07-12 22:56:08,217] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-12 22:56:08,952] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
